server: "mobile-hub.lambdatest.com"
user: "LT_USERNAME"         #Add your LambdaTest username here
accessKey: "LT_ACCESS_KEY"  #Add your LambdaTest accessKey here

common_caps:
  "build": "RSpec Selenium Demo"

browser_caps:
  -
    "isRealMobile": "true"
    "platform": "Android"
    "deviceName": "Galaxy A31"
    "platformVersion": "10"
    "app": "APP_URL"        #Add the app url here